// This file is generated by Slice Machine. Update with care!

import Hero from './Hero'
import ImageSlice from './ImageSlice'
import ImageCards from './ImageCards'
import Quote from './Quote'
import Text from './Text'
import TextWithImage from './TextWithImage'

export { Hero, ImageSlice, ImageCards, Quote, Text, TextWithImage }

export const components = {
  hero: Hero,
  image: ImageSlice,
  image_cards: ImageCards,
  quote: Quote,
  text: Text,
  text_with_image: TextWithImage,
}
